panel:
  title: "Linux Monitoring"
  port: 8080
  entrypoint: "/panel"
  token: "My_secret_token"

collect:
  interval_sec: 1
  history: 120

services:
  manager: "systemd" # openrc | systemd
  limit: 50
  running_only: false
  include: "sshd,crond,nginx"

weather:
  enabled: true
  city: "Moscow"
  token: "open_weather_token"
  units: "metric"
  lang: "ru"
